name: Build Rust

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: |
          .*
