name: Build Rust

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        rustup install nightly
        rustup default nightly
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


    - name: Test
      run: | 
        dir
        cd target/debug/build
        dir

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: |
          target/debug/build
